name: flutter_mapbox
description: Flutter Mapbox.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  mapbox_gl: ^0.16.0
  cached_network_image: ^3.2.3
  location: ^4.4.0
  carousel_slider: ^4.2.1
  dio: ^4.0.4
  flutter_native_splash: ^2.2.16
  supabase_flutter: ^1.9.1
  get: ^4.6.5
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/mapbox.png"


flutter_native_splash:
  color: "#000000"

flutter:

  uses-material-design: true

  assets:
   - assets/config/
   - assets/images/
   - assets/icon/
